# Generated by Django 4.1 on 2023-09-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stuId', models.CharField(max_length=100)),
                ('upgrade_time', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('update_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '专升本学生',
                'verbose_name_plural': '专升本学生',
                'db_table': 'upgrade_student',
            },
        ),
    ]
