# Generated by Django 4.1 on 2023-09-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('late', models.CharField(max_length=100)),
                ('late_time', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('signIn', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '签到统计表',
                'verbose_name_plural': '签到统计表',
                'db_table': 'tb_attendance',
            },
        ),
    ]
